/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 */

#include <stdint.h>
#include "main.h"
#include "Console.h"
#include "ADC.h"




int main(void)
{
	MCU_Clock_Setup();
	Delay_Config();
	Console_Init(USART1, 460800);

//	ADC_Init();





	for(;;)
	{
//		printConsole(USART1, "%f \r\n",Get_IC_Temperature());
//		Delay_ms(100);


	}
}
